spring:
  datasource:
    url: jdbc:h2:mem:todo
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2

server:
  servlet:
    context-path: /api/v1
